<template>
  <div class="testMain"  >
    <test-head :tests="tests"
               :currentTest="currentTest"
               @btnClick="btnClick"
               @testChange="testChange"></test-head>
    <test-body :test="tests[currentTest]"></test-body>
  </div>
</template>

<script>
import testHead from "@/components/content/test/testHead";
import testBody from "@/components/content/test/testBody";
export default {
  name: "testMain",
  components:{
    testHead,
    testBody
  },
  data(){
    return{
      tests:[
        {
          index:1,
          type:'simple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'1啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'1啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'1啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'1啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:2,
          type:'simple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'2啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'2啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'2啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'2啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:3,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:4,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:5,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:6,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:7,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:8,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:9,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
        {
          index:10,
          type:'multiple',
          title:'啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山，请选择正确的答案()',
          data:[
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
            {
              detail:'3啊螺丝扣搭街坊实打手动阀手动阀手动阀手动阀撒旦实大苏打飒飒的撒旦撒啊实打实昆仑山',
              state:false
            },
          ],
        },
      ],
      currentTest:0,
    }
  },
  methods:{
    btnClick(){
      if(this.currentTest<this.tests.length-1){
        this.currentTest++
      }else{
        this.currentTest=0
      }
    },
    testChange(index){
      this.currentTest = index-1
    }
  }
}
</script>

<style scoped>
.testMain{
  width: 1000px;
}
</style>